# Generated by Django 5.0.2 on 2024-02-25 12:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'indexes': [models.Index(fields=['centre'], name='backend_sit_centre_31ea1c_idx'), models.Index(fields=['geometry'], name='backend_sit_geometr_16e81f_idx')],
            },
        ),
    ]
