# Generated by Django 5.0.2 on 2024-03-02 00:25

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='site',
            name='backend_sit_geometr_16e81f_idx',
        ),
        migrations.AddIndex(
            model_name='site',
            index=django.contrib.postgres.indexes.GistIndex(fields=['geometry'], name='backend_sit_geometr_4c5a92_gist'),
        ),
    ]
