# Generated by Django 5.0.2 on 2024-03-11 23:41

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_site_backend_sit_geometr_16e81f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contactable', models.BooleanField(default=False, null=True)),
                ('userlocation', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('site', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('ip', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('name', 'email'),
            },
        ),
        migrations.RemoveIndex(
            model_name='site',
            name='backend_sit_centre_31ea1c_idx',
        ),
        migrations.AddIndex(
            model_name='site',
            index=django.contrib.postgres.indexes.GistIndex(fields=['centre'], name='backend_sit_centre_20c04b_gist'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['name'], name='backend_vot_name_2ff52b_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['email'], name='backend_vot_email_74586c_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['contactable'], name='backend_vot_contact_f04bb1_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['ip'], name='backend_vot_ip_0cb9d9_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=django.contrib.postgres.indexes.GistIndex(fields=['userlocation'], name='backend_vot_userloc_2cc34a_gist'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=django.contrib.postgres.indexes.GistIndex(fields=['site'], name='backend_vot_site_ae5696_gist'),
        ),
    ]
