# Generated by Django 5.0.2 on 2024-03-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_vote_remove_site_backend_sit_centre_31ea1c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vote',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vote',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
