# Generated by Django 5.0.2 on 2024-03-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_vote_email_alter_vote_ip_alter_vote_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='confirmed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['confirmed'], name='backend_vot_confirm_513175_idx'),
        ),
    ]
