# Generated by Django 5.0.2 on 2024-03-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_vote_token_vote_backend_vot_token_a47edd_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ('name', 'email', '-date')},
        ),
        migrations.AddField(
            model_name='vote',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
