# Generated by Django 5.0.2 on 2024-03-15 16:20

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['name'], name='backend_bou_name_276094_idx'), django.contrib.postgres.indexes.GistIndex(fields=['geometry'], name='backend_bou_geometr_84f055_gist')],
            },
        ),
    ]
